<?xml version="1.0" ?><!DOCTYPE gene_cancer_corpus [
	<!ELEMENT gene_cancer_corpus (annotation_unit+)>	
	<!-- The `annotation_unit' element contains 1) an annotation unit as presented to the anotators and 2) the annotations made by the annotators.-->
	<!-- The elements `sentence', `gene', `expression_change_keyword_1', `expression_change_keyword_2' and `cancer_term' together represent an annotation unit as presented to the annotators.-->
	<!-- The `annotation' element contains the annotations made by the annotators, or the values of the four annotation concepts.-->
	<!ELEMENT annotation_unit (sentence, gene, expression_change_keyword_1, expression_change_keyword_2, cancer_term+, annotation)>
	<!ATTLIST annotation_unit id ID #REQUIRED
				  phase (pilot | p1 | p2 | p3) #REQUIRED
				  cancer_type (prostate | breast | ovarian) #REQUIRED >
	<!ELEMENT sentence (#PCDATA)>
	<!ATTLIST sentence pmid CDATA #REQUIRED >
	<!ELEMENT gene (#PCDATA)>
	<!ATTLIST gene range CDATA #REQUIRED >
	<!ELEMENT expression_change_keyword_1 (#PCDATA)>
	<!ATTLIST expression_change_keyword_1 range CDATA #REQUIRED type (None | Gene_expression) #REQUIRED>
	<!ELEMENT expression_change_keyword_2 (#PCDATA)>
	<!ATTLIST expression_change_keyword_2 range CDATA #REQUIRED type (Negative_regulation | Positive_regulation) #REQUIRED>
	<!ELEMENT cancer_term (#PCDATA)>
	<!ATTLIST cancer_term range CDATA #REQUIRED>
	<!ELEMENT annotation (CGE, CCS, IGE, PT)>
	<!ELEMENT CGE EMPTY>
	<!ATTLIST CGE value (increased | decreased) #REQUIRED>
	<!ELEMENT CCS EMPTY>
	<!ATTLIST CCS value (normalTOnormal | normalTOcancer | cancerTOcancer | cancerTOnormal | unidentifiable) #REQUIRED>
	<!ELEMENT IGE EMPTY>
	<!ATTLIST IGE value (up-regulated | down-regulated | unchanged | unidentifiable) #REQUIRED>
	<!ELEMENT PT EMPTY>
	<!ATTLIST PT value (causality | observation) #REQUIRED>
]><gene_cancer_corpus>
<annotation_unit cancer_type="prostate" id="au1" phase="pilot">
<sentence pmid="10945637.s12">Thus, FGF6 is increased in PIN and prostate cancer and can promote the proliferation of the transformed prostatic epithelial cells via paracrine and autocrine mechanisms.</sentence>
<gene range="6-9">FGF6</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="14-22" type="Positive_regulation">increased</expression_change_keyword_2>
<cancer_term range="35-49">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au2" phase="pilot">
<sentence pmid="11722842.s0">Isolation and characterization of the major form of human MUC18 cDNA gene and correlation of MUC18 over-expression in prostate cancer cell lines and tissues with malignant progression.</sentence>
<gene range="93-97">MUC18</gene>
<expression_change_keyword_1 range="99-113" type="Gene_expression">over-expression</expression_change_keyword_1>
<expression_change_keyword_2 range="99-113" type="Positive_regulation">over-expression</expression_change_keyword_2>
<cancer_term range="118-132">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au3" phase="pilot">
<sentence pmid="11722842.s13">We therefore conclude that MUC18 expression is increased during prostate cancer initiation (high grade PIN) and progression to carcinoma, and in metastatic cell lines and metastatic carcinoma.</sentence>
<gene range="27-31">MUC18</gene>
<expression_change_keyword_1 range="33-42" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="47-55" type="Positive_regulation">increased</expression_change_keyword_2>
<cancer_term range="64-78">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au4" phase="pilot">
<sentence pmid="11839683.s9">These results demonstrate that in a sequence-specific manner, RIalpha antisense, via efficient depletion of the growth stimulatory molecule RIalpha, induces growth inhibition, apoptosis, and phenotypic (cell morphology) changes, providing an innovative approach to combat hormone-insensitive prostate cancer cell growth.</sentence>
<gene range="112-146">growth stimulatory molecule RIalpha</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="95-103" type="Negative_regulation">depletion</expression_change_keyword_2>
<cancer_term range="292-306">prostate cancer</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="cancerTOnormal"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au5" phase="pilot">
<sentence pmid="12006585.s2">We have found that Cdc6 expression is down-regulated in prostate cancer as detected by semiquantitative reverse transcriptase-PCR of prostate cell lines and laser-captured microdissected prostate tissues.</sentence>
<gene range="19-22">Cdc6</gene>
<expression_change_keyword_1 range="24-33" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="38-51" type="Negative_regulation">down-regulated</expression_change_keyword_2>
<cancer_term range="56-70">prostate cancer</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au6" phase="pilot">
<sentence pmid="12006585.s4">Furthermore, a 100-fold reduction in the transcription efficiency of the Cdc6 promoter-luciferase construct was noted in the metastatic PC3 cells compared with that in BPH-1 cells.</sentence>
<gene range="73-106">Cdc6 promoter-luciferase construct</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="24-32" type="Negative_regulation">reduction</expression_change_keyword_2>
<cancer_term range="136-138">PC3</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au7" phase="pilot">
<sentence pmid="12409226.s7">Sustained increase of the c-myc gene product was detectable in PC-3 but not in DU-145 cells.</sentence>
<gene range="26-43">c-myc gene product</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="10-17" type="Positive_regulation">increase</expression_change_keyword_2>
<cancer_term range="63-66">PC-3</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au8" phase="pilot">
<sentence pmid="12409226.s8">Concurrently, we demonstrated BN-dependent activation of the transcription factor Elk-1 and significant increase of cell proliferation in both prostate cancer cell lines.</sentence>
<gene range="61-86">transcription factor Elk-1</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="43-52" type="Positive_regulation">activation</expression_change_keyword_2>
<cancer_term range="143-157">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au9" phase="pilot">
<sentence pmid="12433721.s1">Electronic profiling of publicly available expressed sequence tag databases identified a gene, cysteine-rich secretoryprotein-3 (CRISP-3), that is up-regulated in prostate cancer, and of which the expression is relatively prostate-specific.</sentence>
<gene range="129-135">CRISP-3</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="147-158" type="Positive_regulation">up-regulated</expression_change_keyword_2>
<cancer_term range="163-177">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au10" phase="pilot">
<sentence pmid="12569365.s4">Cdc25B is frequently overexpressed in human prostate cancer tissues (29 of 30; 97%).</sentence>
<gene range="0-5">Cdc25B</gene>
<expression_change_keyword_1 range="21-33" type="Gene_expression">overexpressed</expression_change_keyword_1>
<expression_change_keyword_2 range="21-33" type="Positive_regulation">overexpressed</expression_change_keyword_2>
<cancer_term range="44-58">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au11" phase="pilot">
<sentence pmid="12598323.s1">PTOV1 was recently identified as a novel gene and protein during a differential display screening for genes overexpressed in prostate cancer.</sentence>
<gene range="0-4">PTOV1</gene>
<expression_change_keyword_1 range="108-120" type="Gene_expression">overexpressed</expression_change_keyword_1>
<expression_change_keyword_2 range="108-120" type="Positive_regulation">overexpressed</expression_change_keyword_2>
<cancer_term range="125-139">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au12" phase="pilot">
<sentence pmid="12598323.s3">By immunohistochemical analysis, we have found that PTOV1 is overexpressed in 71% of 38 prostate carcinomas and in 80% of samples with prostate intraepithelial neoplasia.</sentence>
<gene range="52-56">PTOV1</gene>
<expression_change_keyword_1 range="61-73" type="Gene_expression">overexpressed</expression_change_keyword_1>
<expression_change_keyword_2 range="61-73" type="Positive_regulation">overexpressed</expression_change_keyword_2>
<cancer_term range="88-106">prostate carcinomas</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au13" phase="pilot">
<sentence pmid="12618764.s0">MEK5 overexpression is associated with metastatic prostate cancer, and stimulates proliferation, MMP-9 expression and invasion.</sentence>
<gene range="0-3">MEK5</gene>
<expression_change_keyword_1 range="5-18" type="Gene_expression">overexpression</expression_change_keyword_1>
<expression_change_keyword_2 range="5-18" type="Positive_regulation">overexpression</expression_change_keyword_2>
<cancer_term range="50-64">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au14" phase="pilot">
<sentence pmid="12875974.s2">The overexpression of Bax inhibitor-1 (BI-1) in prostate carcinoma and prostate cancer cell lines was confirmed by using Northern blot and Western blot analyses.</sentence>
<gene range="39-42">BI-1</gene>
<expression_change_keyword_1 range="4-17" type="Gene_expression">overexpression</expression_change_keyword_1>
<expression_change_keyword_2 range="4-17" type="Positive_regulation">overexpression</expression_change_keyword_2>
<cancer_term range="71-85">prostate cancer</cancer_term>
<cancer_term range="48-65">prostate carcinoma</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au15" phase="pilot">
<sentence pmid="12907652.s9">These observations suggest that U19 is growth inhibitory and tumor suppressive and that the disruption of androgen-dependent growth inhibition via U19 down-regulation is commonly associated with prostate cancer progression.</sentence>
<gene range="147-149">U19</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="151-165" type="Negative_regulation">down-regulation</expression_change_keyword_2>
<cancer_term range="195-209">prostate cancer</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au16" phase="pilot">
<sentence pmid="14744752.s5">First, a comprehensive serial immunohistochemical analysis of primary and metastatic prostate cancer samples showed increased stage-specific expression of IL-11Ralpha during disease progression.</sentence>
<gene range="155-165">IL-11Ralpha</gene>
<expression_change_keyword_1 range="141-150" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="116-124" type="Positive_regulation">increased</expression_change_keyword_2>
<cancer_term range="85-99">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au17" phase="pilot">
<sentence pmid="14744778.s2">We have shown previously that although AP-2 is expressed highly in normal prostatic epithelium, its expression is lost in high-grade prostatic intraepithelial neoplasia and prostate cancer, suggesting that loss of AP-2 plays a role in prostate cancer development.</sentence>
<gene range="214-217">AP-2</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="206-209" type="Negative_regulation">loss</expression_change_keyword_2>
<cancer_term range="173-187">prostate cancer</cancer_term>
<cancer_term range="235-249">prostate cancer</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au18" phase="pilot">
<sentence pmid="14744778.s10">Elucidating the molecular events resulting from loss of AP-2 in the prostate epithelium has implications for the understanding and prevention of the onset of prostate cancer.</sentence>
<gene range="56-59">AP-2</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="48-51" type="Negative_regulation">loss</expression_change_keyword_2>
<cancer_term range="158-172">prostate cancer</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="unidentifiable"/>
<IGE value=""/>
<PT value=""/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au19" phase="pilot">
<sentence pmid="14766760.s7">The interaction between FADD and caspase-8 was inhibited, but abrogation of JNK activity or HIPK3 expression was found to restore this interaction and increased the sensitivity of DU 145 cells to Fas receptor-mediated apoptosis.</sentence>
<gene range="92-96">HIPK3</gene>
<expression_change_keyword_1 range="98-107" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="62-71" type="Negative_regulation">abrogation</expression_change_keyword_2>
<cancer_term range="180-185">DU 145</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="cancerTOnormal"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au20" phase="pilot">
<sentence pmid="15026365.s14">In clinical prostate cancer specimens from patients with varying grades of disease, the stained tissue sections showed high levels of SREBP-1 protein compared with noncancerous prostate tissue.</sentence>
<gene range="134-148">SREBP-1 protein</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="124-129" type="Positive_regulation">levels</expression_change_keyword_2>
<cancer_term range="12-26">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au21" phase="pilot">
<sentence pmid="15026365.s17">In summary, the LNCaP xenograft model of human prostate cancer as well as clinical specimens of prostate cancer demonstrated an up-regulation of SREBPs and their downstream effector genes during progression to androgen independence.</sentence>
<gene range="145-150">SREBPs</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="128-140" type="Positive_regulation">up-regulation</expression_change_keyword_2>
<cancer_term range="47-61">prostate cancer</cancer_term>
<cancer_term range="96-110">prostate cancer</cancer_term>
<cancer_term range="16-20">LNCaP</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au22" phase="pilot">
<sentence pmid="15833840.s1">An increase in the activity of mitogen-activated protein kinase (MAPK) has been correlated with the progression of prostate cancer to advanced disease in humans.</sentence>
<gene range="31-62">mitogen-activated protein kinase</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="3-10" type="Positive_regulation">increase</expression_change_keyword_2>
<cancer_term range="115-129">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au23" phase="pilot">
<sentence pmid="15833840.s3">Increasing RSK isoform 2 (RSK2) levels in the human prostate cancer line, LNCaP, enhanced prostate-specific antigen (PSA) expression, an important diagnostic marker for prostate cancer, whereas inhibiting RSK activity using a RSK-specific inhibitor, 3Ac-SL0101, decreased PSA expression.</sentence>
<gene range="117-119">PSA</gene>
<expression_change_keyword_1 range="122-131" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="81-88" type="Positive_regulation">enhanced</expression_change_keyword_2>
<cancer_term range="52-66">prostate cancer</cancer_term>
<cancer_term range="169-183">prostate cancer</cancer_term>
<cancer_term range="74-78">LNCaP</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au24" phase="pilot">
<sentence pmid="15833840.s3">Increasing RSK isoform 2 (RSK2) levels in the human prostate cancer line, LNCaP, enhanced prostate-specific antigen (PSA) expression, an important diagnostic marker for prostate cancer, whereas inhibiting RSK activity using a RSK-specific inhibitor, 3Ac-SL0101, decreased PSA expression.</sentence>
<gene range="272-274">PSA</gene>
<expression_change_keyword_1 range="276-285" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="262-270" type="Negative_regulation">decreased</expression_change_keyword_2>
<cancer_term range="52-66">prostate cancer</cancer_term>
<cancer_term range="169-183">prostate cancer</cancer_term>
<cancer_term range="74-78">LNCaP</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="unidentifiable"/>
<IGE value=""/>
<PT value=""/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au25" phase="pilot">
<sentence pmid="15837784.s0">Down-regulation of ATM protein sensitizes human prostate cancer cells to radiation-induced apoptosis.</sentence>
<gene range="19-29">ATM protein</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="0-14" type="Negative_regulation">Down-regulation</expression_change_keyword_2>
<cancer_term range="48-62">prostate cancer</cancer_term>
<annotation>
<CGE value="decreased"/>
<CCS value="cancerTOnormal"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au26" phase="pilot">
<sentence pmid="15897876.s7">CBX7 overexpression in LNCaP cells resulted in a slight growth advantage in both androgen-dependent and -independent conditions.</sentence>
<gene range="0-3">CBX7</gene>
<expression_change_keyword_1 range="5-18" type="Gene_expression">overexpression</expression_change_keyword_1>
<expression_change_keyword_2 range="5-18" type="Positive_regulation">overexpression</expression_change_keyword_2>
<cancer_term range="23-27">LNCaP</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au27" phase="pilot">
<sentence pmid="16115918.s1">Cytochrome P450 1B1 (CYP1B1), a dioxin inducible member of the CYP supergene family, is overexpressed in various human malignancies including prostate cancer.</sentence>
<gene range="0-27">Cytochrome P450 1B1 (CYP1B1)</gene>
<expression_change_keyword_1 range="88-100" type="Gene_expression">overexpressed</expression_change_keyword_1>
<expression_change_keyword_2 range="88-100" type="Positive_regulation">overexpressed</expression_change_keyword_2>
<cancer_term range="142-156">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au28" phase="pilot">
<sentence pmid="16424021.s0">Increased expression of osteopontin contributes to the progression of prostate cancer.</sentence>
<gene range="24-34">osteopontin</gene>
<expression_change_keyword_1 range="10-19" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="0-8" type="Positive_regulation">Increased</expression_change_keyword_2>
<cancer_term range="70-84">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au29" phase="pilot">
<sentence pmid="16601286.s0">Increased expression of type 2 3alpha-hydroxysteroid dehydrogenase/type 5 17beta-hydroxysteroid dehydrogenase (AKR1C3) and its relationship with androgen receptor in prostate carcinoma.</sentence>
<gene range="24-117">type 2 3alpha-hydroxysteroid dehydrogenase/type 5 17beta-hydroxysteroid dehydrogenase (AKR1C3)</gene>
<expression_change_keyword_1 range="10-19" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="0-8" type="Positive_regulation">Increased</expression_change_keyword_2>
<cancer_term range="166-183">prostate carcinoma</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="unidentifiable"/>
<IGE value=""/>
<PT value=""/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au30" phase="pilot">
<sentence pmid="16601286.s13">We conclude that elevated expression of AKR1C3 is highly associated with prostate carcinoma.</sentence>
<gene range="40-45">AKR1C3</gene>
<expression_change_keyword_1 range="26-35" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="17-24" type="Positive_regulation">elevated</expression_change_keyword_2>
<cancer_term range="73-90">prostate carcinoma</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au31" phase="pilot">
<sentence pmid="16609016.s9">Kaplan-Meier survival analysis confirmed increased RPL19 expression to be highly predictive of shorter patient survival (P &amp;lt; 0.05), revealing RPL19 to be a sensitive predictor of prostate cancer progression.</sentence>
<gene range="51-55">RPL19</gene>
<expression_change_keyword_1 range="57-66" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="41-49" type="Positive_regulation">increased</expression_change_keyword_2>
<cancer_term range="182-196">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="unidentifiable"/>
<IGE value=""/>
<PT value=""/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au32" phase="pilot">
<sentence pmid="16818616.s6">Transfection-mediated WWOX overexpression in DU145 cells suppressed colony growth (P = 0.0012), and WWOX overexpression by infection with Ad-WWOX virus induced apoptosis through a caspase-dependent mechanism and suppressed cell growth.</sentence>
<gene range="100-103">WWOX</gene>
<expression_change_keyword_1 range="105-118" type="Gene_expression">overexpression</expression_change_keyword_1>
<expression_change_keyword_2 range="105-118" type="Positive_regulation">overexpression</expression_change_keyword_2>
<cancer_term range="45-49">DU145</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="cancerTOnormal"/>
<IGE value="unidentifiable"/>
<PT value="causality"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au33" phase="pilot">
<sentence pmid="17003780.s7">Together, our data suggest that strong Tiam1 overexpression relative to the corresponding benign epithelial cells is a new and independent predictor of decreased DFS for patients with prostate cancer.</sentence>
<gene range="39-43">Tiam1</gene>
<expression_change_keyword_1 range="45-58" type="Gene_expression">overexpression</expression_change_keyword_1>
<expression_change_keyword_2 range="45-58" type="Positive_regulation">overexpression</expression_change_keyword_2>
<cancer_term range="184-198">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="unidentifiable"/>
<IGE value=""/>
<PT value=""/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au34" phase="pilot">
<sentence pmid="17134822.s0">Polycomb-group oncogenes EZH2, BMI1, and RING1 are overexpressed in prostate cancer with adverse pathologic and clinical features.</sentence>
<gene range="0-28">Polycomb-group oncogenes EZH2</gene>
<expression_change_keyword_1 range="51-63" type="Gene_expression">overexpressed</expression_change_keyword_1>
<expression_change_keyword_2 range="51-63" type="Positive_regulation">overexpressed</expression_change_keyword_2>
<cancer_term range="68-82">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au35" phase="pilot">
<sentence pmid="17481580.s4">Out of seven isoforms of gal8, the proto isoform gal8e and our newly discovered proto isoform gal8g were upregulated in LNCaP cells compared to PrEC, whereas the two tandem-repeat isoforms gal8a and gal8b were equally expressed in these cells.</sentence>
<gene range="49-53">gal8e</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="105-115" type="Positive_regulation">upregulated</expression_change_keyword_2>
<cancer_term range="120-124">LNCaP</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au36" phase="pilot">
<sentence pmid="17481580.s4">Out of seven isoforms of gal8, the proto isoform gal8e and our newly discovered proto isoform gal8g were upregulated in LNCaP cells compared to PrEC, whereas the two tandem-repeat isoforms gal8a and gal8b were equally expressed in these cells.</sentence>
<gene range="94-98">gal8g</gene>
<expression_change_keyword_1 range="None" type="None">
None
</expression_change_keyword_1>
<expression_change_keyword_2 range="105-115" type="Positive_regulation">upregulated</expression_change_keyword_2>
<cancer_term range="120-124">LNCaP</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="normalTOcancer"/>
<IGE value="unchanged"/>
<PT value="observation"/>
</annotation></annotation_unit>
<annotation_unit cancer_type="prostate" id="au37" phase="pilot">
<sentence pmid="17513602.s0">Increased expression of cyclin B1 sensitizes prostate cancer cells to apoptosis induced by chemotherapy.</sentence>
<gene range="24-32">cyclin B1</gene>
<expression_change_keyword_1 range="10-19" type="Gene_expression">expression</expression_change_keyword_1>
<expression_change_keyword_2 range="0-8" type="Positive_regulation">Increased</expression_change_keyword_2>
<cancer_term range="45-59">prostate cancer</cancer_term>
<annotation>
<CGE value="increased"/>
<CCS value="cancerTOnormal"/>